export const zones = [
  {
    id: 1,
    name: 'hokkaido',
    region: 1,
    displayName: '北海道',
    short: '北海道',
    kana: 'ホッカイドウ',
    neighbor: [2],
  },
  {
    id: 2,
    name: 'aomori',
    region: 2,
    displayName: '青森県',
    short: '青森',
    kana: 'アオモリ',
    neighbor: [1, 3, 5],
  },
  {
    id: 3,
    name: 'iwate',
    region: 2,
    displayName: '岩手県',
    short: '岩手',
    kana: 'イワテ',
    neighbor: [2, 4, 5],
  },
  {
    id: 4,
    name: 'miyagi',
    region: 2,
    displayName: '宮城県',
    short: '宮城',
    kana: 'ミヤギ',
    neighbor: [3, 5, 6, 7],
  },
  {
    id: 5,
    name: 'akita',
    region: 2,
    displayName: '秋田県',
    short: '秋田',
    kana: 'アキタ',
    neighbor: [2, 3, 4, 6],
  },
  {
    id: 6,
    name: 'yamagata',
    region: 2,
    displayName: '山形県',
    short: '山形',
    kana: 'ヤマガタ',
    neighbor: [4, 5, 7, 15],
  },
  {
    id: 7,
    name: 'fukushima',
    region: 2,
    displayName: '福島県',
    short: '福島',
    kana: 'フクシマ',
    neighbor: [4, 6, 8, 9, 10, 15],
  },
  {
    id: 8,
    name: 'ibaraki',
    region: 3,
    displayName: '茨城県',
    short: '茨城',
    kana: 'イバラキ',
    neighbor: [7, 9, 11, 12],
  },
  {
    id: 9,
    name: 'tochigi',
    region: 3,
    displayName: '栃木県',
    short: '栃木',
    kana: 'トチギ',
    neighbor: [8, 7, 10, 11],
  },
  {
    id: 10,
    name: 'gunma',
    region: 3,
    displayName: '群馬県',
    short: '群馬',
    kana: 'グンマ',
    neighbor: [7, 9, 11, 15, 20],
  },
  {
    id: 11,
    name: 'saitama',
    region: 3,
    displayName: '埼玉県',
    short: '埼玉',
    kana: 'サイタマ',
    neighbor: [8, 9, 10, 12, 13, 19, 20],
  },
  {
    id: 12,
    name: 'chiba',
    region: 3,
    displayName: '千葉県',
    short: '千葉',
    kana: 'チバ',
    neighbor: [8, 11, 13, 14],
  },
  {
    id: 13,
    name: 'tokyo',
    region: 3,
    displayName: '東京都',
    short: '東京',
    kana: 'トウキョウ',
    neighbor: [11, 12, 14, 19],
  },
  {
    id: 14,
    name: 'kanagawa',
    region: 3,
    displayName: '神奈川県',
    short: '神奈川',
    kana: 'カナガワ',
    neighbor: [12, 13, 19, 22],
  },
  {
    id: 15,
    name: 'niigata',
    region: 4,
    displayName: '新潟県',
    short: '新潟',
    kana: 'ニイガタ',
    neighbor: [6, 7, 10, 16, 20],
  },
  {
    id: 16,
    name: 'toyama',
    region: 4,
    displayName: '富山県',
    short: '富山',
    kana: 'トヤマ',
    neighbor: [15, 17, 20, 21],
  },
  {
    id: 17,
    name: 'ishikawa',
    region: 4,
    displayName: '石川県',
    short: '石川',
    kana: 'イシカワ',
    neighbor: [16, 18, 21],
  },
  {
    id: 18,
    name: 'fukui',
    region: 4,
    displayName: '福井県',
    short: '福井',
    kana: 'フクイ',
    neighbor: [17, 21, 25, 26],
  },
  {
    id: 19,
    name: 'yamanashi',
    region: 4,
    displayName: '山梨県',
    short: '山梨',
    kana: 'ヤマナシ',
    neighbor: [11, 13, 14, 20, 22],
  },
  {
    id: 20,
    name: 'nagano',
    region: 4,
    displayName: '長野県',
    short: '長野',
    kana: 'ナガノ',
    neighbor: [10, 11, 15, 16, 19, 21, 22, 23],
  },
  {
    id: 21,
    name: 'gifu',
    region: 4,
    displayName: '岐阜県',
    short: '岐阜',
    kana: 'ギフ',
    neighbor: [16, 17, 18, 20, 23, 24, 25],
  },
  {
    id: 22,
    name: 'shizuoka',
    region: 4,
    displayName: '静岡県',
    short: '静岡',
    kana: 'シズオカ',
    neighbor: [14, 19, 20, 23],
  },
  {
    id: 23,
    name: 'aichi',
    region: 4,
    displayName: '愛知県',
    short: '愛知',
    kana: 'アイチ',
    neighbor: [20, 21, 22, 24],
  },
  {
    id: 24,
    name: 'mie',
    region: 5,
    displayName: '三重県',
    short: '三重',
    kana: 'ミエ',
    neighbor: [21, 23, 25, 26, 29, 30],
  },
  {
    id: 25,
    name: 'shiga',
    region: 5,
    displayName: '滋賀県',
    short: '滋賀',
    kana: 'シガ',
    neighbor: [18, 21, 24, 26],
  },
  {
    id: 26,
    name: 'kyoto',
    region: 5,
    displayName: '京都府',
    short: '京都',
    kana: 'キョウト',
    neighbor: [18, 24, 25, 27, 28, 29],
  },
  {
    id: 27,
    name: 'osaka',
    region: 5,
    displayName: '大阪府',
    short: '大阪',
    kana: 'オオサカ',
    neighbor: [26, 28, 29, 30],
  },
  {
    id: 28,
    name: 'hyogo',
    region: 5,
    displayName: '兵庫県',
    short: '兵庫',
    kana: 'ヒョウゴ',
    neighbor: [26, 27, 30, 31, 33, 36, 37],
  },
  {
    id: 29,
    name: 'nara',
    region: 5,
    displayName: '奈良県',
    short: '奈良',
    kana: 'ナラ',
    neighbor: [24, 26, 27, 30],
  },
  {
    id: 30,
    name: 'wakayama',
    region: 5,
    displayName: '和歌山県',
    short: '和歌山',
    kana: 'ワカヤマ',
    neighbor: [24, 27, 28, 29, 36],
  },
  {
    id: 31,
    name: 'tottori',
    region: 6,
    displayName: '鳥取県',
    short: '鳥取',
    kana: 'トットリ',
    neighbor: [28, 32, 33, 34],
  },
  {
    id: 32,
    name: 'shimane',
    region: 6,
    displayName: '島根県',
    short: '島根',
    kana: 'シマネ',
    neighbor: [31, 34, 35],
  },
  {
    id: 33,
    name: 'okayama',
    region: 6,
    displayName: '岡山県',
    short: '岡山',
    kana: 'オカヤマ',
    neighbor: [28, 31, 34, 37],
  },
  {
    id: 34,
    name: 'hiroshima',
    region: 6,
    displayName: '広島県',
    short: '広島',
    kana: 'ヒロシマ',
    neighbor: [31, 32, 33, 35, 37, 38],
  },
  {
    id: 35,
    name: 'yamaguchi',
    region: 6,
    displayName: '山口県',
    short: '山口',
    kana: 'ヤマグチ',
    neighbor: [32, 34, 38, 40, 44],
  },
  {
    id: 36,
    name: 'tokushima',
    region: 7,
    displayName: '徳島県',
    short: '徳島',
    kana: 'トクシマ',
    neighbor: [28, 30, 37, 38, 39],
  },
  {
    id: 37,
    name: 'kagawa',
    region: 7,
    displayName: '香川県',
    short: '香川',
    kana: 'カガワ',
    neighbor: [28, 33, 34, 36, 38],
  },
  {
    id: 38,
    name: 'ehime',
    region: 7,
    displayName: '愛媛県',
    short: '愛媛',
    kana: 'エヒメ',
    neighbor: [33, 34, 35, 36, 37, 39, 44],
  },
  {
    id: 39,
    name: 'kochi',
    region: 7,
    displayName: '高知県',
    short: '高知',
    kana: 'コウチ',
    neighbor: [36, 38],
  },
  {
    id: 40,
    name: 'fukuoka',
    region: 8,
    displayName: '福岡県',
    short: '福岡',
    kana: 'フクオカ',
    neighbor: [35, 41, 42, 43, 44],
  },
  {
    id: 41,
    name: 'saga',
    region: 8,
    displayName: '佐賀県',
    short: '佐賀',
    kana: 'サガ',
    neighbor: [40, 42],
  },
  {
    id: 42,
    name: 'nagasaki',
    region: 8,
    displayName: '長崎県',
    short: '長崎',
    kana: 'ナガサキ',
    neighbor: [41, 43],
  },
  {
    id: 43,
    name: 'kumamoto',
    region: 8,
    displayName: '熊本県',
    short: '熊本',
    kana: 'クマモト',
    neighbor: [40, 41, 42, 44, 45, 46],
  },
  {
    id: 44,
    name: 'oita',
    region: 8,
    displayName: '大分県',
    short: '大分',
    kana: 'オオイタ',
    neighbor: [35, 38, 40, 43, 45],
  },
  {
    id: 45,
    name: 'miyazaki',
    region: 8,
    displayName: '宮崎県',
    short: '宮崎',
    kana: 'ミヤザキ',
    neighbor: [43, 44, 46],
  },
  {
    id: 46,
    name: 'kagoshima',
    region: 8,
    displayName: '鹿児島県',
    short: '鹿児島',
    kana: 'カゴシマ',
    neighbor: [43, 45, 47],
  },
  {
    id: 47,
    name: 'okinawa',
    region: 8,
    displayName: '沖縄県',
    short: '沖縄',
    kana: 'オキナワ',
    neighbor: [46],
  },
  {
    id: 48,
    name: 'foreign',
    region: 9,
    displayName: '海外',
    short: '海外',
    kana: 'カイガイ',
    neighbor: [],
  },
] as const;

export const zoneNameToDisplayName = (name: string): string => {
  const prefecture = zones.find((p) => p.name === name);
  if (prefecture) {
    return prefecture.displayName;
  }
  return '';
};
